INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Matemáticas', 'Examen de matemáticas para nivel secundario');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Física', 'Examen de física para nivel secundario');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Química', 'Examen de química para nivel secundario');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Biología', 'Examen de biología para nivel secundario');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Historia', 'Examen de historia universal');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Geografía', 'Examen de geografía mundial');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Literatura', 'Examen de literatura clásica');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Filosofía', 'Examen de filosofía moderna');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Informática', 'Examen de fundamentos de informática');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Inglés', 'Examen de comprensión lectora en inglés');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Francés', 'Examen de comprensión lectora en francés');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Arte', 'Examen de historia del arte');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Música', 'Examen de teoría musical');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Educación Física', 'Examen teórico de educación física');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Economía', 'Examen de fundamentos de economía');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Administración', 'Examen de principios de administración');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Contabilidad', 'Examen de contabilidad básica');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Psicología', 'Examen de psicología general');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Sociología', 'Examen de fundamentos de sociología');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Derecho', 'Examen de introducción al derecho');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Derecho', 'Examen de introducción al derecho');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Derecho', 'Examen de introducción al derecho');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Derecho', 'Examen de introducción al derecho');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Derecho', 'Examen de introducción al derecho');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Derecho', 'Examen de introducción al derecho');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Derecho', 'Examen de introducción al derecho');
INSERT INTO tblExamen (Nombre, Descripcion) VALUES ('Examen de Derecho', 'Examen de introducción al derecho');
